project_id = "lxyqqlwbpygeilrriljc"

[functions.admin-create-user]
verify_jwt = false

[functions.distribute-leads]
verify_jwt = false

[functions.cleanup-leads]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false

[functions.import-leads-sheet]
verify_jwt = false
