project_id = "zlijqelcmweqwkivmnag"

[functions.admin-create-user]
verify_jwt = true

[functions.distribute-leads]
verify_jwt = true

[functions.cleanup-leads]
verify_jwt = true

[functions.sync-google-calendar]
verify_jwt = true

[functions.import-leads-sheet]
verify_jwt = true

[functions.webhook-dispatcher]
verify_jwt = true
